### ISSUE TITLE
Use releases for distribution

### ISSUE THREAD

**Issue by ur-fault** [JuliaStolova/Snake#2]
Build of the software generally isn't part of the repository itself (on GitHub or GitLab), but distributed using mechanism called [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

It would be better if you used this [tab](https://github.com/JuliaStolova/Snake/releases) for distribution instead of having it as separate [directory in the repository](https://github.com/JuliaStolova/Snake/tree/main/Snake-Windows).

Just create a new release, add version, and upload the archive of the build.

🤓 🤓 🤓

**Comment by filip2cz** [comment]
He is right

**Comment by JuliaStolova** [comment]
Thank you for informing :D

I'll look at that.
